resolver: lts-8.9
docker:
  enable: false
  image: "liquidhaskell"
packages:
- '.'
- './generic-deriving-newtypeless'
- location:
    git: https://github.com/ucsd-progsys/liquidhaskell
    commit: 05b716191353d7db6d0b33100a9a67ac48bdd5c0
  extra-dep: true
- location:
    git: https://github.com/ucsd-progsys/liquid-fixpoint
    commit: 882137a6aac58badcc483770f24227c579afd06d
  extra-dep: true

extra-deps:
- aeson-0.11.3.0
- csv-table-0.1.0.1
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
- intern-0.9.1.4
- liquid-fixpoint-0.6.0.1
- liquidhaskell-0.8.0.0
- located-base-0.1.1.0

flags:
  liquidhaskell:
    devel: true

extra-package-dbs: []

allow-newer: True
compiler-check: newer-minor
