resolver: lts-8.9
docker:
  enable: false
  image: "liquidhaskell"
packages:
- '.'
- './generic-deriving-newtypeless'
- location:
    git: https://github.com/ucsd-progsys/liquidhaskell
    commit: 259ebc254472918e6275c44099c56d7ff019ea9f
  extra-dep: true
- location:
    git: https://github.com/ucsd-progsys/liquid-fixpoint
    commit: 109a52f23be8d42cef15db222ac30179be58de60
  extra-dep: true

extra-deps:
- aeson-0.11.3.0
- csv-table-0.1.0.1
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
- intern-0.9.1.4
- liquid-fixpoint-0.6.0.1
- liquidhaskell-0.8.0.0
- located-base-0.1.1.0

flags:
  liquidhaskell:
    devel: true

extra-package-dbs: []

allow-newer: True
compiler-check: newer-minor
