resolver: lts-6.27
docker:
  enable: false
  image: "liquidhaskell"
packages:
- '.'
- './generic-deriving-newtypeless'
- location:
    git: https://github.com/ucsd-progsys/liquidhaskell
    commit: 904e6927a97480856fe2c7d2e083f7bc7a0710c5
  extra-dep: true
- location:
    git: https://github.com/christetreault/liquiddesugar
    commit: 792501fdbf75edbdeb496f9e16ee7ddf6fd2decf
  extra-dep: true
- location:
    git: https://github.com/ucsd-progsys/liquid-fixpoint
    commit: 59f25fced058fdf8f0484dc9c176353160b4ad1f
  extra-dep: true

extra-deps:
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
- intern-0.9.1.4
- liquid-fixpoint-0.6.0.1
- liquiddesugar-7.10.0.0
- liquidhaskell-0.7.0.0
- located-base-0.1.1.0

flags:
  liquid-fixpoint:
    devel: true
  liquidhaskell:
    devel: true

extra-package-dbs: []

allow-newer: True
compiler-check: newer-minor
