resolver: lts-8.9
docker:
  enable: false
  image: "liquidhaskell"
packages:
- '.'
- './generic-deriving-newtypeless'
- location:
    git: https://github.com/ucsd-progsys/liquidhaskell
    commit: fb0348020873edf34e242b894cd018cbf57c9166
  extra-dep: true
- location:
    git: https://github.com/ucsd-progsys/liquid-fixpoint
    commit: 7e9823e3f4bf1c2cb4008219134b34e2116c22e5
  extra-dep: true

extra-deps:
- aeson-0.11.3.0
- csv-table-0.1.0.1
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
- intern-0.9.1.4
- liquid-fixpoint-0.6.0.1
- liquidhaskell-0.8.0.0
- located-base-0.1.1.0

flags:
  liquid-fixpoint:
    devel: true
  liquidhaskell:
    devel: true

extra-package-dbs: []

allow-newer: True
compiler-check: newer-minor
